name: "Roam Research backup"

on:
  push:
    branches:
      - master
  schedule:
    - cron: "15 16 * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Backup
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm install
      - run: npm start
        env:
          ROAM_EMAIL: ${{ secrets.roamEmail }}
          ROAM_PASSWORD: ${{ secrets.roamPassword }}
      - name: Get time  
        id: time
        uses: nanzm/get-time-action@v1.0
        with:
          format: 'YYYY-MM-DD-HH-mm-ss'
      - name: rename and move resulting backup
        env:
          TIME: "${{ steps.time.outputs.time }}"
        run: |
          mkdir -p backups
          for f in *.zip; do mv -- "$f" "backups/${f}.${TIME}.zip"; done
      - name: Create commit and tag in release
        run: |
          git add ./backups
          git commit -C ${{github.sha}} --allow-empty
      - name: Push to relase and upload new tag
        run: |
          git push origin release
          
